### ISSUE TITLE
div text content is over flowing from bottom side when we resize.

### ISSUE THREAD

**Issue by AbubakarShf** [AbubakarShf/-BENAZIR-BHUTTO-SHAHEED-UNIVERSITY-website#1]
### **when you resize the content of white container/div is overflow.**
**here is the images of that problem.**
![1white](https://user-images.githubusercontent.com/66548987/118391807-a1e8eb00-b64f-11eb-8419-82ac75bf2e2b.jpg)
![content_overflow](https://user-images.githubusercontent.com/66548987/118391810-a44b4500-b64f-11eb-9dd8-e65897c065d4.jpg)
![3](https://user-images.githubusercontent.com/66548987/118391814-a6ad9f00-b64f-11eb-9189-ad5a637a0b5b.jpg)

**Comment by JAYESH8011** [comment]
hey, I can help with the issue

**Comment by AbubakarShf** [comment]
> 
> 
> hey, I can help with the issue

Thanks alot @JAYESH8011

**Comment by AbubakarShf** [comment]
> 
> 
> > hey, I can help with the issue
> 
> lets resolve that issue :)

I am looking forward

**Comment by AbubakarShf** [comment]
> 
> 
> hey, I can help with the issue

Let's resolve that issue :)

**Comment by JAYESH8011** [comment]
Just add **overflow: hidden;** rule in your div CSS and change the height from vh to max-content , then see if it gets fixed.

**Comment by AbubakarShf** [comment]
> 
> 
> Just add **overflow: hidden;** rule in your div CSS and change the height from vh to max-content , then see if it gets fixed.

okk. i will try it.
